bot:
  timezone: 'Australia/Melbourne'
  guild: SAINT CHADS
  channel: fia-review

  commands:
    - name: create_poll
      group: incident
      description: Create an incident poll between up to 5 drivers.
      func_name: create_incident_poll

    - name: run_job
      group: jobs
      description: Run a generic job from the available list of jobs.
      func_name: run_job

  jobs:
    - name: finalise_polls
      description: Close threads and post summary of incident polls.
      interval: 0 21 * * 0
      func_name: finalise_polls
